""" ESCREVA UM PROGRAMA QUE LEIA O ANO DE NASCIMENTO DE UM JOVEM E INFORME, DE ACORDO COM SUA IDADE:
- SE ELE AINDA VAI SE ALISTAR AO SERVIÇO MILITAR.
- SE É A HORA DE ALISTAR.
- SE JÁ PASSOU DO TEMPO DO ALISTAMENTO.
SEU PROGRAMA TAMBÉM DEVERÁ MOSTRAR O TEMPO QUE FALTA OU QUE PASSOU DO PRAZO."""