""" REFAÇA O EXERCÍCIO 35 DOS TRIÂNGULOS, ACRESCENTANDO O RECURSO DE MOSTRAR QUE TIPO DE TRIÂNGULO SERÁ FORMADO:
- EQUILÁTERO: TODOS OS LADOS IGUAIS
- ISÓSCELES: DOIS LADOS IGUAIS
- ESCALENO: TODOS OS LADOS DIFERENTES"""